version: "3.8"

services:
  db:
    image: postgres:15
    container_name: desafio-db
    restart: always
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
